### PR TITLE
support for asyncpg v0.30.0

### PR DESCRIPTION
**Pull request by trim21**
upstream project is now partially types, so we should find a way to sync typing in both package.

There is a problem with new `connect` argument in `create_pool`, it has same type with `connection.connect` and there is no `typeof` in typing, so it will need to write whole definition twice

### CODE REVIEW

**Comment by bryanforbes** [comment]
Thanks for the PR! I'll try to get some time to review it over the next couple of days.

**Comment by trim21** [comment]
👀

**Comment by bryanforbes** [comment]
Sorry for the delay. I'll get this worked on over the weekend.

**Comment by bryanforbes** [comment]
Thanks again for your PR. I made a few changes and pushed it to `master` with your name attached.

**Pull request closed without merging**
